### PR TITLE
feat: add advanced zoom example story

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
close https://github.com/zakodium/react-plot/issues/240

### CODE REVIEW

**Comment by lpatiny** [comment]
Just use 'HCys100OH' as default value for `mf` (instead of HCys10OH). It will be more interesting.

There is still the bestPeaks recalculation on zoom changing missing but otherwise it looks great.

**Comment by wadjih-bencheikh18** [comment]
bestPeaks recalculation done

**Comment by lpatiny** [comment]
Works as expected, thanks. @targos it is the example we spoke about when the 'best' peaks are recalculate on zoom. If you could have a quick look at the implementation would be great.

Here is the direct link to the storybook: https://deploy-preview-244--react-plot.netlify.app/?path=/story/experimental-spectra-mass--advanced-mass-example

**Comment by targos** [comment]
implementation is good

**Pull request merged**
