### PR TITLE
feat: add keyboard events

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium/react-plot/issues/331

### CODE REVIEW

**Comment by targos** [comment]
I'm really not convinced we should support keyboard events inside plots. It is not intuitive to need to have focus on the plot for them to work. What kind of example would you implement with this feature?

**Comment by wadjih-bencheikh18** [comment]
> I'm really not convinced we should support keyboard events inside plots. It is not intuitive to need to have focus on the plot for them to work. What kind of example would you implement with this feature?

In the old version we used it to implement grab functionality (click alt btn)
We need it in the initialisation of max/min also to change cursor style

**Comment by wadjih-bencheikh18** [comment]
> > 
> 
> We don't need it to initialize max/min because the mouse event contains the information of which modifier keys are currently pressed.


I thought mouse event only contains coordinates
But yes we can change tracking result to get them thanks

**Comment by targos** [comment]
> But yes we can change tracking result to get them thanks

No need to change tracking result. The information are available in `result.event`

**Comment by wadjih-bencheikh18** [comment]
> No need to change tracking result. The information are available in `result.event`

could you please explain how ? because i did't find how to get max / min

**Comment by wadjih-bencheikh18** [comment]
and also we're not inside plotContext provider

**Comment by targos** [comment]
> could you please explain how ? because i did't find how to get max / min

I suggested something in my review of your other pull request.

I'm going to close this PR for now because we think that keyboard events can always be handled from the parent of `Plot` as they don't need access to the plot's state.

**Pull request closed without merging**
