### PR TITLE
feat: add option for getting ticks inside the axis

### LINKED ISSUE #54: support putting ticks inside the plot

### PR DESCRIPTION
**Pull request by maasencioh**
closes #54

### CODE REVIEW

**Comment by stropitek** [comment]
What about a prop that sets the tick length, so that you can both control the size and the position inside / outside with one prop?

**Comment by maasencioh** [comment]
@stropitek I thought the same, but then if you want to invert it you should add a negative value, that's not very user friendly right?

**Comment by stropitek** [comment]
Yes fair enough, it would have to be properly documented. But maybe better to have size just control the size.

**Comment by stropitek** [comment]
I'm not sure if the tick direction option should be a boolean or a string.

`<Axis tickInside />` vs `<Axis tickDirection="inside" />` with the default value being `outside`

In that case a boolean would make sense because there are only 2 possibilities but I still find the first one a bit awkward compared to the second one. But I could go either way.

**Review by stropitek — APPROVED** [review]

**Comment by maasencioh** [comment]
Maybe `tickEmbedded`, following the labels name convention?

**Comment by stropitek** [comment]
> Maybe `tickEmbedded`, following the labels name convention?

yes that is better than `tickInside` IMO

**Pull request merged**
