### PR TITLE
Feat : simple time scale (Date type not allowed)

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : #78

### CODE REVIEW

**Review by stropitek — COMMENTED** [review]
Is it still necessary to keep the calls to `toNumber` in various places. Shouldn't the only place where it is called be the stories which use data and need to convert to numbers?

**Comment by wadjih-bencheikh18** [comment]
> Is it still necessary to keep the calls to `toNumber` in various places?. Shouldn't the only place where it is called be the stories which use data and need to convert to numbers?

Yes because in react-d3-utils they accept DATE type so scale.invert return DATE |number so we need to use toNumber()

**Comment by stropitek** [comment]
There is a small conflict

**Comment by wadjih-bencheikh18** [comment]
conflict fixed

**Pull request merged**
