### PR TITLE
docs: Weather Chart

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium/react-plot/issues/79

Story: https://deploy-preview-349--react-plot.netlify.app/?path=/story/examples-weather-chart--weather-chart

### CODE REVIEW

**Comment by lpatiny** [comment]
Please only put the bar series for the rain and  not the range series

Please fix the unit of the rain: (mm/h)

For the rain scale please put it between min=0, max=5

Please add some vertical grid (1px, light grey)

What are there those vertical white lines ? Is this a white grid ???

image

**Comment by wadjih-bencheikh18** [comment]
no there is no vertical grid the data is made of diffrent lineseries / rangeSeries that are not perfectly linked

**Comment by wadjih-bencheikh18** [comment]
> For the rain scale please put it between min=0, max=5

i added an issue for this

**Comment by lpatiny** [comment]
> no there is no vertical grid the data is made of different lineseries / rangeSeries that are not perfectly linked (the last point in a Serie is not the start of the next one

Ok seems normal. Please prepare the data so that you have only one series rather than one series per day. This will solve the problem (and is the correct way in fact).

**Comment by wadjih-bencheikh18** [comment]
@lpatiny fixed

**Comment by lpatiny** [comment]
But I don't see the bar series with the rain anymore. Nothing is blue in the bottom

image

**Comment by wadjih-bencheikh18** [comment]
> Nothing is blue in the bottom

its working perfectly in local 
image

the problem is in the draft deployment

**Comment by wadjih-bencheikh18** [comment]
the reason why barseries is not working here is the same as mass example

**Comment by lpatiny** [comment]
Ok so now that the other PR is merged: https://github.com/zakodium/react-plot/pull/351 it should be fixed if we rebase.

**Pull request merged**
